name: check

on:
  push:
    branches:
      - main
      - release-**
  pull_request:
    branches:
      - main
      - release-**

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.23", "1.22", "1.20"]
    name: Go ${{ matrix.go }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...
        env:
          GOMAXPROCS: 4

      - name: check
        run: |
          if [ ! -z "`git status -s`" ]; then
            echo "Following files are not consistent with CI:"
            git status -s
            git diff
            exit 1
          fi
